#!/usr/bin/env bash

# TODO implement modules path discovery (non-Homebrew installations)
modules_pkg_prefix=/opt/homebrew/opt/modules
modulecmd=$modules_pkg_prefix/bin/modulecmd

# Setting the siteconfig with the environment variable configures the siteconfig
# _during_ the modules system initialization. This avoids the issue where
# procedures and variables defined in the siteconfig aren't visible to modules
# loaded within the user's modulerc (~/.modulerc) if the siteconfig is
# configured using `module config extra_siteconfig`.
export MODULES_SITECONFIG=${XDG_CONFIG_HOME:-$HOME/.config}/cx.darryl.modules/siteconfig.tcl
export MODULERCFILE=${XDG_CONFIG_HOME:-$HOME/.config}/cx.darryl.modules/modulerc
eval "$($modulecmd bash autoinit)"

completion_script=$modules_pkg_prefix/init/bash_completion

[[ -f $completion_script ]] && [[ -r $completion_script ]] && source $completion_script

module config mcookie_check eval
