#!/usr/bin/env bash

alias ..="cd .."            # Up one level
alias ...="cd ../.."        # Up two levels
alias ....="cd ../../.."    # Up three levels


# Single-letter aliases
# ---------------------

alias a="cd ~/apps"
alias b="cd -"              # Return to previous directory
alias c="clear"
alias d="cd ~/dotfiles"
alias e="cd ~/exercism"
alias f="open ."            # Open current directory in Finder
alias k="pkill -i"          # Kill app by name
alias h="cd ~"              # Home directory
alias p="cd ~/projects"
alias r="cd ~/resources"
alias t="type"
alias u="cd ~/uno"
alias v="vim"


# Two and three letter aliases
# ----------------------------

alias cpu="top -F -R -o cpu"
alias dl="youtube-dl"
alias nf="neofetch --config ~/dotfiles/bash/neofetch.conf"
alias nff="neofetch --config ~/dotfiles/bash/neofetch-all.conf"
alias rh="runhaskell"
alias spd="speedtest-cli"
alias ta="type -a"
alias tl="cd /"
alias vol="cd /volumes"

# Use GNU `ls` if installed (gls via Homebrew on macOS)
if [[ "$(uname -s)" == "Linux"  || "$(uname -s)" == "CYGWIN_NT-6.1" ]]; then
    alias l="ls -Fh --color --group-directories-first"
    alias la="ls -AFh --color --group-directories-first"
    alias ll="ls -AFhlo --color --group-directories-first"
elif [[ "$(command -v gls)" ]]; then
    alias l="gls -Fh --color --group-directories-first"
    alias la="gls -AFh --color --group-directories-first"
    alias ll="gls -AFhlo --color --group-directories-first"
else
    alias l="ls -F"
    alias la="ls -AF"
    alias ll="ls -AFlo"
fi


# Longer aliases
# --------------

alias cmdkill="pkill -i"
alias empty="sudo rm -rf ~/.Trash/*"                        # Empty macOS trash
alias ffmon="yabai -m config focus_follows_mouse autofocus" # Enable focus follow mouse
alias ffmoff="yabai -m config focus_follows_mouse off"      # Disable focus follow mouse
alias fkill="killall Finder"
alias kill="kill -9"
alias nawk="/usr/bin/awk"                                   # One True AWK
alias rebash="source ~/.bash_profile"                       # Reload .bash_profile
alias reyabai="brew services restart yabai"                 # Restart yabai
alias rekey="brew services restart skhd"                    # Restart skhd
alias pgrep="pgrep -i"
alias pipes="/usr/local/bin/pipes.sh/"
alias temp="osx-cpu-temp"
alias tempf="osx-cpu-temp -F"
alias tidy="find . -type f -name '*.DS_Store' -ls -delete"  # Delete all `.DS_Store` files
alias tree="tree -C"                                        # Always use colored `tree` output
alias update="sudo softwareupdate -aiR"                     # Install all macOS updates and restart system
