#!/usr/bin/env bash

# Single-letter aliases
# ---------------------

alias g="git"


# Two and three letter aliases
# ----------------------------

alias l="ls -F"
alias la="ls -AF"
alias ll="ls -AFlo"


# Longer aliases
# --------------

alias kill="kill -9"
alias rebash="source ~/.bash_profile"                       # Reload .bash_profile
