#!/usr/bin/env bash

# Super quick note
function n () {
  title=$(date +%Y-%m-%d)
  note=$*
  echo $(date): $note >> ~/Desktop/Note_${title}.txt
}


# Check price of individual cryptocurrency
#
# Dependency: jq (brew install jq)
#
# Usage: `coin btc` (use ticker symbol; case-insensitive)
# Output: BTC: $8,999.99 (Coinbase)

function coin () {
  ticker=$(curl -s "https://min-api.cryptocompare.com/data/pricemultifull?fsyms="${1^^}"&tsyms=USD")
  price=$(echo $ticker | printf "%.2f\n" $(jq -cr '.RAW.'${1^^}'.USD.PRICE'))
  exchange=$(echo $ticker | jq -cr '.DISPLAY.'${1^^}'.USD.LASTMARKET')
  echo "${1^^}: \$"$price "("$exchange")"
}
