#!/usr/bin/env bash

# Git
# ---

alias ga="git add"
alias gall="git add --all"
alias gb="git branch"
alias gba="git branch --all"
alias gc="git commit"
alias gca="git commit --amend"
alias gcl="git clone --recursive"           # Clone including any submodules
alias gco="git checkout"
alias gcp="git cherry-pick"
alias gd="git diff"
alias gf="git fetch --dry-run --verbose"
alias gg="git grep"
alias gge="git grep -P"
alias ggei="git grep -Pi"
alias gl="git log --oneline -n 10"
alias gp="git push"
alias gpl="git pull"
alias grb="git rebase"
alias gs="git status -sb"

# Quick commit with message without quotes
function qc() {
    message=$*

    if [[ $message ]]; then   
        git commit -m "${message}"
    else
        printf "\\033[31mERROR:\\033[0m Commit message required\\n"
        return 1
    fi
}
