#!/usr/bin/env bash

# This file holds configs/funcitons/aliases for hue-cli (Philips Hue)
# Install hue-cli with "sudo gem install hue-cli"

alias strip="hue 1"
alias lamp="hue 2"

alias outrun="office on && hue 1 brightness 165 && hue 1 color 0.2017 0.3274 && hue 2 brightness 165 && hue 2 color 0.3235 0.1758"
alias night="office on && hue lights brightness 125 && hue lights color 0.47 0.41"

function office ()
{
  cmd=$*
  # Commands are on, off, flash, blink, solid

  if  [[ $cmd ]]; then
    hue 1 "${cmd}"
    hue 2 "${cmd}"
  else
    printf "\\033[31mERROR:\\033[0m No command given\\n"
    return 1
  fi
}
