#!/usr/bin/env bash

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias c="clear"

# Shortcuts
alias tl="cd /"
alias h="cd ~"
alias b="cd -"
alias a="cd ~/applications"
alias d="cd ~/dotfiles"
alias e="cd ~/exercism"
alias p="cd ~/projects"
alias u="cd ~/UNO"
alias v="vim"
alias vol="cd /volumes"

# Always use colored `tree` output
alias tree="tree -C"

# Use GNU `ls` if installed (gls via Homebrew on macOS)
if [[ "$(uname -s)" == "Linux" ]]; then
  alias l="ls -Fh --color --group-directories-first"
  alias la="ls -AFh --color --group-directories-first"
  alias ll="ls -AFhlo --color --group-directories-first"
elif [[ "$(command -v gls)" ]]; then
  alias l="gls -Fh --color --group-directories-first"
  alias la="gls -AFh --color --group-directories-first"
  alias ll="gls -AFhlo --color --group-directories-first"
else
  alias l="ls -F"
  alias la="ls -AF"
  alias ll="ls -AFlo"
fi

# Changes directory and lists contents in one command wow
function cs() {
  local DIR=$1
  cd ${DIR} && gls -Fh --color --group-directories-first
}
