#!/usr/bin/env bash

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias c="clear"

# Shortcuts
alias tl="cd /"
alias h="cd ~"
alias b="cd -"
alias p="cd ~/projects"
alias d="cd ~/dotfiles"
alias a="cd ~/applications"
alias v="cd /volumes"
alias e="vim"

#tree
alias t="tree -C"

# ls
alias l="ls -F --color -h --group-directories-first"
alias la="ls -AF --color -h --group-directories-first"
alias ll="ls -AFlo --color -h --group-directories-first"

# Changes directory and lists contents in one command wow
function cs() {
  dir=$*
  cd $dir && ls -F --color -h --group-directories-first
}
