#!/usr/bin/env bash

# $PATH is left-associative; utilities sourced first take precedence.
#
# e.g. here we force Brew-installed `curl` to override the system `curl`
# but we don't allow non-prefixed GNU Coreutils to override default 
# system utilities.

if [[ "$(uname -s)" == "Darwin" ]]; then
  export PATH="/usr/local/opt/curl/bin:$PATH:/usr/local/opt/coreutils/libexec/gnubin:/Users/darryl/.rbenv/bin:/Users/darryl/.rbenv/shims"
elif [[ "$(uname -s)" == "Linux" ]]; then
  export PATH="$PATH:/home/darryl/.rbenv/bin:/home/darryl/.rbenv/shims"
fi
