#!/usr/bin/env bash

# Displays red prompt if root
# Displays blue prompt during SSH session

if [[ $(id -u) -eq 0 ]]; then
  PS1="\[\e[1;31m\][\h:\u]\[\e[m\] \w \[\e[1m\]ϟ\[\e[m\] "
elif [[ -n "$SSH_CLIENT" ]]; then
  PS1="\[\e[1;34m\][\h:\u]\[\e[m\] \w \[\e[1m\]ϟ\[\e[m\] " 
else
  PS1="\w \[\e[1m\]ϟ\[\e[m\] "
fi
