#!/usr/bin/env bash

# This file contains functions which allow me to quick-search a variety of websites
# via the command-line

# Baseball-Reference
# Using 'the' in the search query is Baseball-Reference's version of "I'm Feeling Lucky"
function bbref () {
  term=$*

  if [[ $term ]]; then
    open -a Safari "https://www.baseball-reference.com/search/search.fcgi?search=the+${term}"
  else
    echo -e "\e[31mERROR:\e[0m Invalid search parameters"
  fi
}

# Pro-Football-Reference
function pfref () {
  term=$*

  if [[ $term ]]; then
    open -a Safari "https://www.pro-football-reference.com/search/search.fcgi?search=the+${term}"
  else
    echo -e "\e[31mERROR:\e[0m Invalid search parameters"
  fi
}
