tap "cjbassi/gotop"
tap "dart-lang/dart"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "sass/sass"
brew "awscli"
brew "bash"
brew "cabal-install"
brew "cask"
brew "cmake"
brew "cmatrix"
brew "coreutils"
brew "ctags"
brew "curl"
brew "dash"
brew "diff-so-fancy"
brew "doctl"
brew "duti"
brew "exercism"
brew "ffmpeg"
brew "gawk"
brew "gettext"
brew "ghc"
brew "gibo"
brew "git"
brew "gnupg"
brew "gotop"
brew "haskell-stack"
brew "hub"
brew "hugo"
brew "jq"
brew "koekeishiya/formulae/chunkwm"
brew "koekeishiya/formulae/skhd"
brew "llvm"
brew "mas"
brew "mawk"
brew "nasm"
brew "neofetch"
brew "nmap"
brew "pandoc"
brew "pipes-sh"
brew "python@2", link: false
brew "python@3"
brew "rename"
brew "sass/sass/sass"
brew "shc"
brew "shellcheck"
brew "speedtest-cli"
brew "stow"
brew "tldr"
brew "toilet"
brew "unar"
brew "watch"
brew "wget"
brew "youtube-dl"
cask "1password"
cask "adobe-creative-cloud"
cask "electrum"
cask "font-envy-code-r"
cask "font-hasklig"
cask "font-open-sans"
cask "font-open-sans-condensed"
cask "font-oswald"
cask "font-share"
cask "font-share-tech"
cask "font-share-tech-mono"
cask "font-source-code-pro"
cask "font-source-sans-pro"
cask "font-source-serif-pro"
cask "font-space-mono"
cask "google-chrome"
cask "iina"
cask "iterm2"
cask "keybase"
cask "marked"
cask "openemu"
cask "philips-hue-sync"
cask "qlcolorcode"
cask "qlstephen"
cask "sony-ps4-remote-play"
cask "spotify"
mas "Airmail 3", id: 918858936
mas "Calcbot", id: 931657367
mas "Cascadea", id: 1432182561
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Spillo", id: 873245660
mas "Wipr", id: 1320666476
