#!/usr/bin/env bash

modules_init=/opt/homebrew/opt/modules/init/bash

if [[ -f $modules_init && -r $modules_init ]]; then
    source $modules_init
fi

export MODULES_ROOTDIR=~/.modules
module use $MODULES_ROOTDIR/modulefiles/Core
