#!/usr/bin/env bash

# TODO implement modules path discovery (non-Homebrew installations), and
# possibly accommodate Lmod
modules_pkg_prefix=/opt/homebrew/opt/modules

modules_init=$modules_pkg_prefix/init/bash
modules_completion=$modules_pkg_prefix/init/bash_completion

for file in $modules_init $modules_completion; do
    if [[ -f $file && -r $file ]]; then
        source $file
    fi
done

module config extra_siteconfig ~/.modules/siteconfig.tcl
